// Curated exercise library, grouped by the muscle group each movement is
// logged against. Naming follows the "Movement (Equipment)" convention
// common to training apps, so variants of the same lift stay adjacent in
// the dropdown.
//
// Two flags keep logs honest rather than letting the form record nonsense:
//   bodyweight — no external load, so the weight field is hidden
//   timed      — measured in seconds held, not repetitions
//
// The flags are independent, not a two-value enum. A weighted plank is timed
// but loaded; a pistol squat is bodyweight but counted in reps; a farmer's
// carry is both timed and loaded. Anything timed is excluded from rep and
// volume totals, since seconds under tension don't convert to either.
//
// A movement appears under exactly one group: the one it's primarily
// training. Compound lifts are filed under the muscle doing most of the
// work (deadlift under back, dip under chest), so the body map doesn't
// double-count a single session.
export const EXERCISES = {
  shoulders: [
    { name: "Overhead Press (Barbell)" },
    { name: "Shoulder Press (Dumbbell)" },
    { name: "Arnold Press (Dumbbell)" },
    { name: "Shoulder Press (Machine)" },
    { name: "Push Press (Barbell)" },
    { name: "Z Press (Barbell)" },
    { name: "Landmine Press" },
    { name: "Bradford Press (Barbell)" },
    { name: "Lateral Raise (Dumbbell)" },
    { name: "Lateral Raise (Cable)" },
    { name: "Lateral Raise (Machine)" },
    { name: "Front Raise (Dumbbell)" },
    { name: "Front Raise (Plate)" },
    { name: "Rear Delt Fly (Dumbbell)" },
    { name: "Rear Delt Fly (Cable)" },
    { name: "Reverse Pec Deck (Machine)" },
    { name: "Face Pull (Cable)" },
    { name: "Upright Row (Barbell)" },
    { name: "Upright Row (Cable)" },
    { name: "Pike Push-Up", bodyweight: true },
    { name: "Handstand Push-Up", bodyweight: true },
  ],
  chest: [
    { name: "Bench Press (Barbell)" },
    { name: "Bench Press (Dumbbell)" },
    { name: "Wide Grip Bench Press (Barbell)" },
    { name: "Incline Bench Press (Barbell)" },
    { name: "Incline Bench Press (Dumbbell)" },
    { name: "Decline Bench Press (Barbell)" },
    { name: "Bench Press (Smith Machine)" },
    { name: "Floor Press (Barbell)" },
    { name: "Floor Press (Dumbbell)" },
    { name: "Chest Press (Machine)" },
    { name: "Chest Press (Cable)" },
    { name: "Chest Fly (Dumbbell)" },
    { name: "Incline Chest Fly (Dumbbell)" },
    { name: "Cable Crossover" },
    { name: "Low to High Cable Fly" },
    { name: "Incline Cable Fly" },
    { name: "Pec Deck (Machine)" },
    { name: "Svend Press (Plate)" },
    { name: "Push-Up", bodyweight: true },
    { name: "Incline Push-Up", bodyweight: true },
    { name: "Decline Push-Up", bodyweight: true },
    { name: "Dip", bodyweight: true },
  ],
  back: [
    { name: "Deadlift (Barbell)" },
    { name: "Sumo Deadlift (Barbell)" },
    { name: "Trap Bar Deadlift" },
    { name: "Rack Pull (Barbell)" },
    { name: "Good Morning (Barbell)" },
    { name: "Pull-Up", bodyweight: true },
    { name: "Chin-Up", bodyweight: true },
    { name: "Inverted Row", bodyweight: true },
    { name: "Lat Pulldown (Cable)" },
    { name: "Wide Grip Lat Pulldown (Cable)" },
    { name: "Close Grip Lat Pulldown (Cable)" },
    { name: "Single Arm Lat Pulldown (Cable)" },
    { name: "Bent Over Row (Barbell)" },
    { name: "Pendlay Row (Barbell)" },
    { name: "Seated Row (Cable)" },
    { name: "Single Arm Row (Dumbbell)" },
    { name: "Chest Supported Row (Machine)" },
    { name: "Meadows Row (Landmine)" },
    { name: "T-Bar Row" },
    { name: "Straight Arm Pulldown (Cable)" },
    { name: "Shrug (Dumbbell)" },
    { name: "Shrug (Barbell)" },
    { name: "Back Extension", bodyweight: true },
    { name: "Superman Hold", bodyweight: true, timed: true },
  ],
  arms: [
    { name: "Bicep Curl (Barbell)" },
    { name: "Bicep Curl (Dumbbell)" },
    { name: "Bicep Curl (EZ Bar)" },
    { name: "Hammer Curl (Dumbbell)" },
    { name: "Hammer Curl (Cable)" },
    { name: "Incline Curl (Dumbbell)" },
    { name: "Preacher Curl (Machine)" },
    { name: "Spider Curl (Dumbbell)" },
    { name: "Concentration Curl (Dumbbell)" },
    { name: "Drag Curl (Barbell)" },
    { name: "Reverse Curl (Barbell)" },
    { name: "Zottman Curl (Dumbbell)" },
    { name: "Cable Curl" },
    { name: "21s (Barbell)" },
    { name: "Triceps Pushdown (Cable)" },
    { name: "Rope Pushdown (Cable)" },
    { name: "Overhead Triceps Extension (Dumbbell)" },
    { name: "Overhead Rope Extension (Cable)" },
    { name: "Skullcrusher (Barbell)" },
    { name: "JM Press (Barbell)" },
    { name: "Close Grip Bench Press (Barbell)" },
    { name: "Triceps Kickback (Dumbbell)" },
    { name: "Triceps Dip (Machine)" },
    { name: "Diamond Push-Up", bodyweight: true },
    { name: "Bench Dip", bodyweight: true },
    { name: "Wrist Curl (Dumbbell)" },
    { name: "Reverse Wrist Curl (Dumbbell)" },
    { name: "Farmer's Carry (Dumbbell)", timed: true },
  ],
  abs: [
    { name: "Crunch", bodyweight: true },
    { name: "Sit-Up", bodyweight: true },
    { name: "Decline Sit-Up", bodyweight: true },
    { name: "Bicycle Crunch", bodyweight: true },
    { name: "Reverse Crunch", bodyweight: true },
    { name: "V-Up", bodyweight: true },
    { name: "Hanging Leg Raise", bodyweight: true },
    { name: "Toes to Bar", bodyweight: true },
    { name: "Dragon Flag", bodyweight: true },
    { name: "Dead Bug", bodyweight: true },
    { name: "Cable Crunch" },
    { name: "Cable Woodchop" },
    { name: "Pallof Press (Cable)" },
    { name: "Russian Twist" },
    { name: "Ab Wheel Rollout", bodyweight: true },
    { name: "Plank", bodyweight: true, timed: true },
    { name: "Weighted Plank", timed: true },
    { name: "Side Plank", bodyweight: true, timed: true },
    { name: "Hollow Body Hold", bodyweight: true, timed: true },
    { name: "L-Sit Hold", bodyweight: true, timed: true },
    { name: "Flutter Kick", bodyweight: true, timed: true },
    { name: "Mountain Climber", bodyweight: true, timed: true },
  ],
  legs: [
    { name: "Back Squat (Barbell)" },
    { name: "Front Squat (Barbell)" },
    { name: "Pause Squat (Barbell)" },
    { name: "Box Squat (Barbell)" },
    { name: "Squat (Smith Machine)" },
    { name: "Hack Squat (Machine)" },
    { name: "Belt Squat (Machine)" },
    { name: "Goblet Squat (Dumbbell)" },
    { name: "Sumo Squat (Dumbbell)" },
    { name: "Leg Press (Machine)" },
    { name: "Romanian Deadlift (Barbell)" },
    { name: "Romanian Deadlift (Dumbbell)" },
    { name: "Bulgarian Split Squat (Dumbbell)" },
    { name: "Walking Lunge (Dumbbell)" },
    { name: "Reverse Lunge (Dumbbell)" },
    { name: "Curtsy Lunge (Dumbbell)" },
    { name: "Leg Extension (Machine)" },
    { name: "Lying Leg Curl (Machine)" },
    { name: "Seated Leg Curl (Machine)" },
    { name: "Nordic Curl", bodyweight: true },
    { name: "Hip Thrust (Barbell)" },
    { name: "Glute Bridge", bodyweight: true },
    { name: "Cable Kickback" },
    { name: "Hip Abduction (Machine)" },
    { name: "Hip Adduction (Machine)" },
    { name: "Step-Up (Dumbbell)" },
    { name: "Sissy Squat", bodyweight: true },
    { name: "Pistol Squat", bodyweight: true },
    { name: "Wall Sit", bodyweight: true, timed: true },
    { name: "Sled Push", timed: true },
  ],
  calves: [
    { name: "Standing Calf Raise (Machine)" },
    { name: "Standing Calf Raise (Dumbbell)" },
    { name: "Seated Calf Raise (Machine)" },
    { name: "Calf Raise (Smith Machine)" },
    { name: "Donkey Calf Raise" },
    { name: "Calf Press (Leg Press)" },
    { name: "Single Leg Calf Raise (Dumbbell)" },
    { name: "Tibialis Raise", bodyweight: true },
    { name: "Calf Raise", bodyweight: true },
    { name: "Jump Rope", bodyweight: true, timed: true },
  ],
};

// Looks a movement up by name. Returns null for anything not in the
// library — logs written before this existed hold free text, and their
// rows still have to render.
export function findExercise(bodyGroup, name) {
  return (EXERCISES[bodyGroup] || []).find((e) => e.name === name) || null;
}
